name: CI

on: [push, pull_request]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: NodeJS setup
      uses: actions/setup-node@v4
      with:
        node-version: 20.13.1

    - name: NPM install
      run: npm install

    - name: Eslint
      run: npm run lint

  deploy:
    environment: production
    runs-on: ubuntu-latest
    needs: build
    concurrency: deploy-group

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
    
      - name: Fly.io cli setup
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Fly.io deployment
        run: flyctl deploy --remote-only
